Description: >
  Udacity Capstone Kubernetes Cluster.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Udacity-${ID}
      GroupDescription: Allow port 22 and port 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity-capstone-devops
      ImageId: ami-07651f0c4c315a529 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Installing Docker"
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get -y update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          sudo service docker start
          echo "Installing Minikube"
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          echo "docker to root"
          sudo groupadd docker
          sudo usermod -aG docker $USER
          newgrp docker
          echo "start the kubernetes cluster"
          minikube start --driver=docker
          alias kubectl="minikube kubectl --"
          minikube kubectl -- get po -A

Outputs:
  PublicIp:
    Description: Server Public IP
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub "${ID}-PublicIp"