apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: devops-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-capstone
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone
        image: fikrihelmi17/devops-capstone
        ports:
        - containerPort: 80